services:
    db:
        image: postgres
        container_name: cantor_postgres
        restart: on-failure
        environment:
          POSTGRES_PASSWORD: admin
          POSTGRES_USER: admin 
          POSTGRES_DB: cantor  
        ports: 
          - '5432:5432'

